spring:
  profiles: default
  jackson:
    default-property-inclusion: non_null
  mvc:
    async:
      request-timeout: 3600000
  batch:
    job:
      enabled: false

logging:
  level: "DEBUG"

security:
  ignored: /**

server:
  compression:
    enabled: true
    min-response-size: 1
  session:
    persistent: true
    cookie:
      http-only: true
      path: "/"
  port: 8080
  context-path: "/"

datasource:
  doosan:
    driver-class-name: "${DB_DRIVER:org.mariadb.jdbc.Driver}"
    url: "${DB_URL:jdbc:mariadb://demo-db:3306/demo?useUnicode=true&charaterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull}"
    user-name: "${DB_USER:demo}"
    password: "${DB_PASSWORD:password!}"
    initial-size: 10
    max-active: 20
    max-idle: 20
    min-idle: 10
    max-wait: 0